// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr_WreeqH3G4CjMFomMc_gKx1euU-0SA4',
    appId: '1:715043575706:web:5671630ba3824b7aac4c23',
    messagingSenderId: '715043575706',
    projectId: 'chatapplication-4e5e8',
    authDomain: 'chatapplication-4e5e8.firebaseapp.com',
    storageBucket: 'chatapplication-4e5e8.firebasestorage.app',
    measurementId: 'G-PE34KXVZJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRS7nGjS8KWs6WRlzJuEBAl60Sg01uo8A',
    appId: '1:715043575706:android:481360fbf24bde87ac4c23',
    messagingSenderId: '715043575706',
    projectId: 'chatapplication-4e5e8',
    storageBucket: 'chatapplication-4e5e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM8PxdMTGb2Td1ZI73eErKN0LH0eZkN-0',
    appId: '1:715043575706:ios:2a6fb3883bf9bfb6ac4c23',
    messagingSenderId: '715043575706',
    projectId: 'chatapplication-4e5e8',
    storageBucket: 'chatapplication-4e5e8.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr_WreeqH3G4CjMFomMc_gKx1euU-0SA4',
    appId: '1:715043575706:web:2b5b4241b5577202ac4c23',
    messagingSenderId: '715043575706',
    projectId: 'chatapplication-4e5e8',
    authDomain: 'chatapplication-4e5e8.firebaseapp.com',
    storageBucket: 'chatapplication-4e5e8.firebasestorage.app',
    measurementId: 'G-2TKL1X77NE',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM8PxdMTGb2Td1ZI73eErKN0LH0eZkN-0',
    appId: '1:715043575706:ios:2a6fb3883bf9bfb6ac4c23',
    messagingSenderId: '715043575706',
    projectId: 'chatapplication-4e5e8',
    storageBucket: 'chatapplication-4e5e8.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

}