// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDft4TdN2TC7nsJ9P8qorsbASnm-gb1Xo8',
    appId: '1:719065730202:web:eb7c180e23d5b46d33e323',
    messagingSenderId: '719065730202',
    projectId: 'chat-app-39f17',
    authDomain: 'chat-app-39f17.firebaseapp.com',
    storageBucket: 'chat-app-39f17.firebasestorage.app',
    measurementId: 'G-FXS5DQ45PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwFYAtP2NS8m80gT7fn5z3noeBX3Ui6IA',
    appId: '1:719065730202:android:a72c14deae080b1a33e323',
    messagingSenderId: '719065730202',
    projectId: 'chat-app-39f17',
    storageBucket: 'chat-app-39f17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOhtdcxmPPwHxVQ6gIvGyifkduTa2X1UI',
    appId: '1:719065730202:ios:eb3e342e7f9f220a33e323',
    messagingSenderId: '719065730202',
    projectId: 'chat-app-39f17',
    storageBucket: 'chat-app-39f17.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDft4TdN2TC7nsJ9P8qorsbASnm-gb1Xo8',
    appId: '1:719065730202:web:48f5fc3e447b48cd33e323',
    messagingSenderId: '719065730202',
    projectId: 'chat-app-39f17',
    authDomain: 'chat-app-39f17.firebaseapp.com',
    storageBucket: 'chat-app-39f17.firebasestorage.app',
    measurementId: 'G-6GX54V49GE',
  );
}
